# Generated by Django 6.0 on 2025-12-12 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('realisateur', models.CharField(max_length=255)),
                ('acteurs', models.TextField(help_text='Liste des acteurs séparés par des virgules')),
                ('duree', models.CharField(help_text='Ex: 2h 30min', max_length=50)),
                ('age_min', models.CharField(default='Tous publics', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text="Lien vers l'affiche du film")),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours', models.CharField(help_text='Jours de la semaine (ex: Lundi,Mercredi,Vendredi)', max_length=255)),
                ('heure', models.TimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='api.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='api.film')),
            ],
        ),
    ]
