# Generated by Django 6.0 on 2025-12-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours', models.CharField(help_text='Jours de la semaine (ex: Lundi,Mercredi,Vendredi)', max_length=255)),
                ('heure', models.TimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='api.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='api.film')),
            ],
        ),
        migrations.DeleteModel(
            name='Seance',
        ),
    ]
