# Generated by Django 6.0 on 2026-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='langue',
            field=models.CharField(default='Français', help_text='Ex: VOSTFR, VF', max_length=100),
        ),
    ]
